version: '3.3'

services:
  postgres:
    build:
      context: pgvector
    container_name: pgvector_container
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5434:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  my_ocr_app:
    build: .
    container_name: my_ocr_app
    ports:
      - "8868:8868"
    depends_on:
      - postgres
    environment:
      POSTGRES_HOST: ${POSTGRES_HOST}
      POSTGRES_PORT: ${POSTGRES_PORT}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      OpenAIKey: ${OpenAIKey}
      rec_image_shape: ${rec_image_shape}
      det_yaml_path: ${det_yaml_path}
      rec_yaml_path: ${rec_yaml_path}
      rec_char_dict_path: ${rec_char_dict_path}
      rec_model_path: ${rec_model_path}
      det_model_path: ${det_model_path}
      cls_model_path: ${cls_model_path}
    volumes:
      - ./model:/app/model

volumes:
  pgdata:
